name = "portfolio-website"
compatibility_date = "2024-08-09"
workers_dev = true

[site]
bucket = "./.svelte-kit/output/client"

[[kv_namespaces]]
binding = "JAY_STUFF"
id = "a23d2beb82dd4e1cb98143dfcf8cb55e"

[env.production]
route = "portfolio-website-9oe.pages.dev/*"
